# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_3.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1835, 860)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.disp = QtWidgets.QWidget(self.centralwidget)
        self.disp.setStyleSheet("background-color: rgb(237, 240, 239);")
        self.disp.setObjectName("disp")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.disp)
        self.gridLayout_2.setContentsMargins(100, 0, 100, 0)
        self.gridLayout_2.setSpacing(30)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.psp_container = QtWidgets.QWidget(self.disp)
        self.psp_container.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.psp_container.setObjectName("psp_container")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.psp_container)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_4 = QtWidgets.QLabel(self.psp_container)
        self.label_4.setMinimumSize(QtCore.QSize(0, 30))
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 0, 0, 1, 1)
        self.psp_plot = PlotWidget(self.psp_container)
        self.psp_plot.setObjectName("psp_plot")
        self.gridLayout_5.addWidget(self.psp_plot, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.psp_container, 1, 1, 1, 1)
        self.result_container = QtWidgets.QWidget(self.disp)
        self.result_container.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.result_container.setObjectName("result_container")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.result_container)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.input_class_value = QtWidgets.QLabel(self.result_container)
        self.input_class_value.setStyleSheet("QLabel {\n"
"font-family: \"Arial\";\n"
"font-size: 30px;\n"
"color : rgb(219,61,1);\n"
"}")
        self.input_class_value.setText("")
        self.input_class_value.setAlignment(QtCore.Qt.AlignCenter)
        self.input_class_value.setObjectName("input_class_value")
        self.gridLayout_6.addWidget(self.input_class_value, 1, 0, 1, 1)
        self.output_class_value = QtWidgets.QLabel(self.result_container)
        self.output_class_value.setStyleSheet("QLabel {\n"
"font-family: \"Arial\";\n"
"font-size: 30px;\n"
"color : rgb(219,61,1);\n"
"}")
        self.output_class_value.setText("")
        self.output_class_value.setAlignment(QtCore.Qt.AlignCenter)
        self.output_class_value.setObjectName("output_class_value")
        self.gridLayout_6.addWidget(self.output_class_value, 1, 1, 1, 1)
        self.input_class_text = QtWidgets.QLabel(self.result_container)
        self.input_class_text.setObjectName("input_class_text")
        self.gridLayout_6.addWidget(self.input_class_text, 2, 0, 1, 1)
        self.output_class_text = QtWidgets.QLabel(self.result_container)
        self.output_class_text.setObjectName("output_class_text")
        self.gridLayout_6.addWidget(self.output_class_text, 2, 1, 1, 1)
        self.spike_count_value = QtWidgets.QLabel(self.result_container)
        self.spike_count_value.setStyleSheet("QLabel {\n"
"font-family: \"Arial\";\n"
"font-size: 30px;\n"
"color : rgb(219,61,1);\n"
"}")
        self.spike_count_value.setText("")
        self.spike_count_value.setAlignment(QtCore.Qt.AlignCenter)
        self.spike_count_value.setObjectName("spike_count_value")
        self.gridLayout_6.addWidget(self.spike_count_value, 1, 2, 1, 1)
        self.spike_count_text = QtWidgets.QLabel(self.result_container)
        self.spike_count_text.setObjectName("spike_count_text")
        self.gridLayout_6.addWidget(self.spike_count_text, 2, 2, 1, 1)
        self.result_title = QtWidgets.QLabel(self.result_container)
        self.result_title.setMinimumSize(QtCore.QSize(0, 30))
        self.result_title.setMaximumSize(QtCore.QSize(16777215, 30))
        self.result_title.setObjectName("result_title")
        self.gridLayout_6.addWidget(self.result_title, 0, 0, 1, 3)
        self.gridLayout_2.addWidget(self.result_container, 1, 0, 1, 1)
        self.voltage_container = QtWidgets.QWidget(self.disp)
        self.voltage_container.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.voltage_container.setObjectName("voltage_container")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.voltage_container)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_5 = QtWidgets.QLabel(self.voltage_container)
        self.label_5.setMinimumSize(QtCore.QSize(0, 30))
        self.label_5.setObjectName("label_5")
        self.gridLayout_8.addWidget(self.label_5, 0, 0, 1, 1)
        self.voltage_plot = PlotWidget(self.voltage_container)
        self.voltage_plot.setObjectName("voltage_plot")
        self.gridLayout_8.addWidget(self.voltage_plot, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.voltage_container, 2, 0, 1, 1)
        self.outspike_container = QtWidgets.QWidget(self.disp)
        self.outspike_container.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.outspike_container.setObjectName("outspike_container")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.outspike_container)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_6 = QtWidgets.QLabel(self.outspike_container)
        self.label_6.setMinimumSize(QtCore.QSize(0, 30))
        self.label_6.setObjectName("label_6")
        self.gridLayout_7.addWidget(self.label_6, 0, 0, 1, 1)
        self.outspike_plot = PlotWidget(self.outspike_container)
        self.outspike_plot.setObjectName("outspike_plot")
        self.gridLayout_7.addWidget(self.outspike_plot, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.outspike_container, 2, 1, 1, 1)
        self.raw_data_container = QtWidgets.QWidget(self.disp)
        self.raw_data_container.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.raw_data_container.setObjectName("raw_data_container")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.raw_data_container)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.raw_data_label = QtWidgets.QLabel(self.raw_data_container)
        self.raw_data_label.setMinimumSize(QtCore.QSize(0, 30))
        self.raw_data_label.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.raw_data_label.setObjectName("raw_data_label")
        self.gridLayout_4.addWidget(self.raw_data_label, 0, 0, 1, 1)
        self.raw_data_plot = PlotWidget(self.raw_data_container)
        self.raw_data_plot.setObjectName("raw_data_plot")
        self.gridLayout_4.addWidget(self.raw_data_plot, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.raw_data_container, 0, 0, 1, 1)
        self.inspike_container = QtWidgets.QWidget(self.disp)
        self.inspike_container.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.inspike_container.setObjectName("inspike_container")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.inspike_container)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.inspike_container)
        self.label_2.setMinimumSize(QtCore.QSize(0, 30))
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.inspike_plot = PlotWidget(self.inspike_container)
        self.inspike_plot.setObjectName("inspike_plot")
        self.gridLayout_3.addWidget(self.inspike_plot, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.inspike_container, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.disp, 1, 1, 1, 1)
        self.banner = QtWidgets.QWidget(self.centralwidget)
        self.banner.setMinimumSize(QtCore.QSize(0, 100))
        self.banner.setMaximumSize(QtCore.QSize(16777215, 100))
        self.banner.setObjectName("banner")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.banner)
        self.gridLayout_10.setContentsMargins(100, 0, 0, 0)
        self.gridLayout_10.setSpacing(0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.banner_logo = QtWidgets.QLabel(self.banner)
        self.banner_logo.setMaximumSize(QtCore.QSize(300, 16777215))
        self.banner_logo.setText("")
        self.banner_logo.setObjectName("banner_logo")
        self.gridLayout_10.addWidget(self.banner_logo, 0, 0, 1, 1)
        self.title_label = QtWidgets.QLabel(self.banner)
        self.title_label.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.gridLayout_10.addWidget(self.title_label, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.banner, 0, 1, 1, 1)
        self.control_panel = QtWidgets.QWidget(self.centralwidget)
        self.control_panel.setMinimumSize(QtCore.QSize(100, 0))
        self.control_panel.setMaximumSize(QtCore.QSize(250, 16777215))
        self.control_panel.setStyleSheet("/*#control_panel {background-color:  rgb(173, 179, 184);}*/")
        self.control_panel.setObjectName("control_panel")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.control_panel)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.listw = QtWidgets.QListWidget(self.control_panel)
        self.listw.setObjectName("listw")
        self.gridLayout_9.addWidget(self.listw, 6, 0, 1, 1)
        self.auto_check_box = QtWidgets.QCheckBox(self.control_panel)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.auto_check_box.setFont(font)
        self.auto_check_box.setObjectName("auto_check_box")
        self.gridLayout_9.addWidget(self.auto_check_box, 4, 0, 1, 1)
        self.input_class_label = QtWidgets.QLabel(self.control_panel)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.input_class_label.setFont(font)
        self.input_class_label.setObjectName("input_class_label")
        self.gridLayout_9.addWidget(self.input_class_label, 5, 0, 1, 1)
        self.btn = QtWidgets.QToolButton(self.control_panel)
        self.btn.setMinimumSize(QtCore.QSize(0, 20))
        self.btn.setMaximumSize(QtCore.QSize(400, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.btn.setFont(font)
        self.btn.setObjectName("btn")
        self.gridLayout_9.addWidget(self.btn, 1, 0, 1, 1)
        self.dropdown_patterns = ComboBox(self.control_panel)
        self.dropdown_patterns.setObjectName("dropdown_patterns")
        self.gridLayout_9.addWidget(self.dropdown_patterns, 3, 0, 1, 1)
        self.logo = QtWidgets.QLabel(self.control_panel)
        self.logo.setMinimumSize(QtCore.QSize(128, 128))
        self.logo.setMaximumSize(QtCore.QSize(300, 300))
        self.logo.setStyleSheet("background-color: rgb(212, 69, 1);")
        self.logo.setText("")
        self.logo.setObjectName("logo")
        self.gridLayout_9.addWidget(self.logo, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.control_panel)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_9.addWidget(self.label, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.control_panel, 0, 0, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1835, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-family:\'Arial\'; font-size:10pt; font-weight:600; color:#32aede;\">Synapse Spike Response</span></p></body></html>"))
        self.input_class_text.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:5px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:10pt; color:#6f777d;\">Input</span></p>\n"
"<p align=\"center\" style=\" margin-top:5px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:10pt; color:#6f777d;\">Class</span></p></body></html>"))
        self.output_class_text.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:5px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:10pt; color:#6f777d;\">Output</span></p>\n"
"<p align=\"center\" style=\" margin-top:5px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:10pt; color:#6f777d;\">Class</span></p></body></html>"))
        self.spike_count_text.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:5px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:10pt; color:#6f777d;\">Spike</span></p>\n"
"<p align=\"center\" style=\" margin-top:5px; margin-bottom:5px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:10pt; color:#6f777d;\">Count</span></p></body></html>"))
        self.result_title.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-family:\'Arial\'; font-size:10pt; font-weight:600; color:#32aede;\">Result</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-family:\'Arial\'; font-size:10pt; font-weight:600; color:#32aede;\">Membrane Potential</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-family:\'Arial\'; font-size:10pt; font-weight:600; color:#32aede;\">Output Spike Train</span></p></body></html>"))
        self.raw_data_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-family:\'Arial\'; font-size:10pt; font-weight:600; color:#32aede;\">Input Stimulus</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-family:\'Arial\'; font-size:10pt; font-weight:600; color:#32aede;\">Input Spike Train</span></p></body></html>"))
        self.title_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:x-large; font-weight:600; color:#6f777d;\">Neuromorphic System for Temporal Data Classification</span></p></body></html>"))
        self.auto_check_box.setText(_translate("MainWindow", "Auto demo"))
        self.input_class_label.setText(_translate("MainWindow", "Result"))
        self.btn.setText(_translate("MainWindow", "Run"))
        self.label.setText(_translate("MainWindow", "Select input class"))

from pyqtgraph import ComboBox, PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

